# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/limonata',
                'doc_host': 'https://sarraahr.github.io',
                'git_url': 'https://github.com/sarraahr/limonata',
                'lib_path': 'limonata'},
  'syms': {}}
